FROM debian:bookworm-slim

RUN apt-get update \
	&& apt-get install -y --no-install-recommends bash curl ca-certificates jq unzip \
	&& rm -rf /var/lib/apt/lists/*

COPY deploy/github-artifact-dl.sh /opt/server/dl.sh
RUN chmod +x /opt/server/dl.sh

WORKDIR /opt/server

RUN ./dl.sh

ENTRYPOINT ["./server-arm64"]
